name: KLIO branch build

on:
  push:
    branches:
      - main
      - 'releases/**'
permissions:
  contents: read

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - darwin
          - linux
          - windows
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        env:
          GOOS_VAR: ${{ matrix.os }}
          OS: ${{ matrix.os }}
          TAG: ${{ github.ref_name }}
        run: | 
          GOOS=$GOOS_VAR go build -o klio-$TAG-$OS ./cmd/klio/...
          ls klio-$TAG-$OS

  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: |
          go test -v ./... -covermode count -coverprofile coverage.out