name: KLIO release push

on:
  release:
    types: [published]
permissions:
  contents: read

jobs:

  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - darwin
          - linux
          - windows
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        env:
          GOOS_VAR: ${{ matrix.os }}
          OS: ${{ matrix.os }}
          TAG: ${{ github.ref_name }}
        run: |
          GOOS=$GOOS_VAR go build -o klio-$TAG-$OS ./cmd/klio/...
          ls klio-$TAG-$OS

      - name: Push
        uses: AButler/upload-release-assets@v2.0
        with:
          files: klio-v*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}