name: KLIO branch build

on:
  push:
    tags:
      - v1.[0-9]+.[0-9]+
    branches:
      - main
      - develop
permissions:
  contents: read

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - darwin
          - linux
          - windows
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: GOOS=$${{ matrix.os }} go build -v ./cmd/klio/... -o klio-$${{ github.ref_name }}-$${{ matrix.os }}

      - name: Push
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name,'v') }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: klio-v*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}


  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: |
          go test -v ./... -covermode count -coverprofile coverage.out