name: KLIO tag build

on:
  push:
    tags:
      - v1.[0-9]+.[0-9]+
permissions:
  contents: read

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - darwin
          - linux
          - windows
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get the version
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build
        env:
          GOOS_VAR: ${{ matrix.os }}
          TAG: ${{ steps.get_tag.outputs.VERSION }}
        run: | 
          GOOS=$GOOS_VAR go build -o klio-$TAG-$GOOS_VAR ./cmd/klio/...
          ls klio-$TAG-$OS

      - name: Push
        if: ${{ github.ref_type == 'tag' }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: klio-v*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.get_tag.outputs.VERSION }}
